--- #YAML:1.0
name:               Data-Dumper-Concise-Aligned
version:            0.21
abstract:           even less indentation plus string prefix
author:
    - Jeremy Mates <jmates@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Scalar::Util:  0
    Test::More:    0
    Text::Wrap:    0
resources:
    homepage:    http://github.com/thrig/Data-Dumper-Concise-Aligned
    license:     http://dev.perl.org/licenses/
    repository:  http://github.com/thrig/Data-Dumper-Concise-Aligned
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
